# Generated by Django 4.0 on 2021-12-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=255, verbose_name='Название книги')),
                ('name_author', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('surname_author', models.CharField(max_length=50, verbose_name='Фамилия автора')),
                ('date_of_publication', models.DateField()),
                ('publisher', models.CharField(choices=[('ast', 'АСТ'), ('eksmo', 'Эксмо')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
