# Generated by Django 4.0 on 2021-12-17 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='salary',
        ),
    ]
