# Generated by Django 4.0 on 2021-12-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shop', '0002_remove_book_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
